### ISSUE TITLE
Formatting doesn't update after clicking 'definitely buy'

### ISSUE THREAD

**Issue by kevinb456** [kitspace/bom-builder#27]
Row still shaded. Cell colour doesn't update to reflect selection.

Also confusing because can get more than one part which is "definitely buy" - may want in some rare cases, but generally I think selecting "definitely buy" should deselect any previous.

**Comment by kasbah** [comment]
I think there is a subtle issue here where the "selected line" grey is overriding the other formatting but I am not sure it's worth tackling since I am going to replace the whole grid anyway. 

"definitely buy" needs to have the final say otherwise there is no way for the user to override to automatic component selection. We can re-think this with the re-design.
